
%% Print


disp(['SARS-CoV-2 na Slovensku'])
disp(['============================'])
disp(['* Analýza ',datestr(now),''])
disp(' ')
disp(['SEIR homogénný infektologický model'])
disp(['bez vitálnej dynamiky (aktualny do konca dna):'])
disp(['(Krátkodobá predikcia s parametrami na základe údajov.)'])
disp(['(Parametre nekonvergujú správne pre chýbajúce dáta na vyliecené pripady a umrtia.)'])
disp(['----------------------------'])
disp(['Overené prípady: ',num2str(round(NdSIRnext)),' (do konca dna)'])
disp(['Nové overené prípady: ',num2str(NdSIRnext-Nd(end)),' (do konca dna)'])
disp(['Celkový predpokladaný pocet nakazených: ',num2str(IsimPred(round(symptoms)+2))])
disp(['Predpokladaný dátum 1000+ overených prípadov: ',datestr(d1+max(Day)+min(find(IsimPred>1000)))])
if (d0est<31)
disp(['Predpokladaný dátum prvého nakazenia: ',datestr(d1-d0est)])
end
%disp(['Predpokladaný skutocný pocet infikovaných nultý den: ',num2str(round(N0est)),' (6-Mar-2020)'])
disp(['Faktor nárastu: ',num2str(round((gFSIR*10))/10),'%'])
disp(['Zdvojenie poctu prípadov za: ',num2str( round((70/((gFSIR))*10))/10),' [dní]'])
%disp(['Odhad základného reprodukcného císla R0: ',num2str(round(R0est*10)/10),', (MSE: ',num2str(MSE),')'])
disp(['Miera rýchlosti infekcie 1/beta: ',num2str(round(1/betaEst*10)/10),' [dni], krátkodobý fit'])
disp(['Miera latencie infekcie 1/sigma: ',num2str(round(1/sigmaEst*10)/10),' [dni], krátkodobý fit'])
disp(['Miera odstránenia prípadov gamma: ',num2str(gammaEst),', krátkodobý fit'])
disp(['Percentuálna kvalita zhody modelu (akt. infekcie): ',num2str(round(fitPerc*10)/10),' %, MSE: ',num2str(round(MSE))])
%disp(['Miera odstránenia prípadov 1/gamma: ',num2str(round(1/gammaEst*10)/10),', (MSE: ',num2str(MSE),')'])
disp(' ')
disp('Exponenciálny model: (aktualny do konca dna)')
disp(['----------------------------'])
disp(['Overené prípady: ',num2str(NdPredicted(max(Day)+1)),' (',num2str(NdPredLow(2)),'-',num2str(NdPredHigh(2)),')']) %,'(',num2str(NdPredLow(max(Day)+1)),'-',NdPredHigh(max(Day)+1),')'])
disp(['Nové overené prípady: ',num2str(NdPredicted(max(Day)+1)-Nd(end)),' (',num2str(NdPredLow(2)-Nd(end)),'-',num2str(NdPredHigh(2)-Nd(end)),')']) %,'(',num2str(NdPredLow(max(Day)+1)),'-',NdPredHigh(max(Day)+1),')'])
disp(['Celkový predpokladaný pocet nakazených: ',num2str(NdSymptoms(max(Day)+1)),' (',num2str(NdSymptomsLow(max(Day)+1)),'-',num2str(NdSymptomsHigh(max(Day)+1)),')'])
%disp(['Predpokladaný dátum 100+ overených prípadov: ',datestr(d1+min(find(NdPredicted>100)))])
disp(['Predpokladaný dátum 1000+ overených prípadov: ',datestr(d1+min(find(NdPredicted>1000)))])
if (firstCase>31)
disp(['Predpokladaný dátum prvého nakazenia: ',datestr(d1+firstCase)])
end
disp(['Predpokladaný skutocný pocet infikovaných nultý den: ',num2str(round(N0)),' (',num2str(round(ci(1,2))),'-',num2str(round(ci(2,2))),'), (6-Mar-2020)'])
disp(['Faktor nárastu: ',num2str(round((gF-1)*100*10)/10),'% (',num2str(round((ci(1,1)-1)*100*10)/10),'%-',num2str(round((ci(2,1)-1)*100*10)/10),'%)'])
disp(['Zdvojenie poctu prípadov za: ',num2str(round((70/((gF-1)*100))*10)/10),' dní'])
disp(['Kvalita zhody modelu R^2 ',num2str(R2)])
disp(' ')

disp('Poynomiálny model: (aktualny do konca dna)')
disp(['----------------------------'])
if (NdPredictedPoly(max(Day)+1)>Nd(end))
disp(['Overené prípady: ',num2str(NdPredictedPoly(max(Day)+1))]) %,'(',num2str(NdPredLow(max(Day)+1)),'-',NdPredHigh(max(Day)+1),')'])
disp(['Nové overené prípady: ',num2str(NdPredictedPoly(max(Day)+1)-Nd(end))]) %,'(',num2str(NdPredLow(max(Day)+1)),'-',NdPredHigh(max(Day)+1),')'])
end
disp(['Celkový predpokladaný pocet nakazených: ',num2str(NdSymptomsPoly(max(Day)+1))])
disp(['Predpokladaný dátum 1000+ overených prípadov: ',datestr(d1+min(find(NdPredictedPoly>1000)))])
%disp(['Predpokladaný dátum prvého nakazenia: ',datestr(d1+firstCasePoly)])
%disp(['Predpokladaný skutocný pocet infikovaných nultý den: ',num2str(round(N0)),' (',num2str(round(ci(1,2))),'-',num2str(round(ci(2,2))),'), (6-Mar-2020)'])
disp(['Faktor nárastu (priemer, posledný týžden): ',num2str(round( gFPoly*10)/10),'%'])
disp(['Zdvojenie poctu prípadov za: ',num2str(round(70/gFPoly*10)/10),' dní'])
disp(['Kvalita zhody modelu R^2 ',num2str(R2Poly)])
disp(' ')

disp(['Stav testovania k ',datestr(dt-1),' (vratane)'])
disp(['----------------------------'])
disp(['Celkove testy na mil. obyvatelov: ',num2str(round(popTest(end)))])
disp(['Nove testy za den na mil. obyvatelov: ',num2str( round(newTest(end)/popSize))])
disp(['Pomer pozitívnych testov: ',num2str(round(Confirmed(end)/newTest(end)*100*10)/10),'%'])
disp(['Denná zmena intenzity testovania: ',num2str(round(changeTest)),'%'])
disp(['Tyzdenny trend intenzity testovania: ',num2str(round((testA*10))/10),'% (lineárny fit)'])
disp(['============================='])
disp(['Viac na: http://covid19.gergelytakacs.com'])